let age = 18;
console.log(age > 18 ? "True" : "False");
console.log(age === 18 ? "True" : "False");
console.log(age < 18 ? "True " : "False");
let Country = "Pakistan";
console.log(Country === "Pakistan" ? "True" : "False");
console.log(Country === "pakistan" ? "True" : "False");
let gender = "female";
console.log(gender === "Male" ? "True" : "False");
console.log(gender === "female" ? "True" : "False");
console.log(gender === "Female" ? "True" : "False");
export {};
