let Name = "Afra";
console.log(Name === "afra");
console.log(Name === "Afra");
let strng = "CAT";
console.log(strng.toLocaleLowerCase() === "cat");
let x = 255;
console.log(x === 5);
console.log(x !== 255);
console.log(x === 255);
console.log(x <= 200);
console.log(x >= 255);
console.log(x < 500);
console.log(x > 55);
let num1 = 10;
let num2 = 30;
let num3 = 20;
console.log(num1 > num2 && num1 > num3);
console.log(num1 < num2 && num2 > num3);
console.log(num3 > num2 || num3 > num1);
let arr = [3, 10.3, 5, 7];
console.log(arr.includes(5));
console.log(!arr.includes(7));
console.log(arr.includes(10.3));
export {};
